#!/bin/sh
# This cript get called after all other system services 
# have been started at boot on router
# ---------------------------------------------------------
# Run my script every 10 minutes 
cru a wanreset "*/10 * * * * /jffs/scripts/cron_wan_public.sh"